# Generated by Django 6.0.2 on 2026-02-17 11:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, help_text="Country this event applies to ('MV', 'LK', 'ALL' for global)", max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('religious', 'Religious Holiday'), ('national', 'National Holiday'), ('festival', 'Festival'), ('school', 'School Holiday'), ('sports', 'Sporting Event'), ('conference', 'Conference / Exhibition'), ('cultural', 'Cultural Event'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('impact_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Expected impact on demand', max_length=10)),
                ('demand_uplift_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated demand uplift percentage', max_digits=5)),
                ('source_markets', models.CharField(blank=True, help_text="Comma-separated source markets affected (e.g., 'Italy,Germany' or blank for all)", max_length=500)),
                ('recurring', models.BooleanField(default=False, help_text='Does this event recur annually?')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Event',
                'verbose_name_plural': 'Market Events',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('import_type', models.CharField(choices=[('arrival_report', 'Country Arrival Report'), ('event', 'Market Events'), ('economic', 'Economic Indicators'), ('benchmark', 'Industry Benchmarks')], max_length=30)),
                ('column_map', models.JSONField(default=dict)),
                ('value_transforms', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('source_headers', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Import Template',
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('import_type', models.CharField(choices=[('arrival_report', 'Country Arrival Report'), ('event', 'Market Events'), ('economic', 'Economic Indicators'), ('benchmark', 'Industry Benchmarks')], max_length=30)),
                ('country_code', models.CharField(blank=True, default='MV', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('column_map_used', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_imports', to='platform_data.platformimporttemplate')),
            ],
            options={
                'verbose_name': 'Platform File Import',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketArrivalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2 country code (e.g., 'MV' for Maldives)", max_length=2)),
                ('report_period', models.DateField(help_text='First day of the reporting period (e.g., 2026-01-01 for Jan 2026)')),
                ('origin_country', models.CharField(help_text="Tourist source market (e.g., 'Italy', 'Germany', 'China')", max_length=100)),
                ('arrivals', models.PositiveIntegerField(default=0, help_text='Number of tourist arrivals from this country')),
                ('market_share_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Market share percentage', max_digits=5, null=True)),
                ('yoy_change_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Year-over-year change percentage', max_digits=7, null=True)),
                ('source_report', models.CharField(blank=True, help_text="Source reference (e.g., 'MoT Monthly Report Jan 2026')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records', to='platform_data.platformfileimport')),
            ],
            options={
                'verbose_name': 'Market Arrival Data',
                'verbose_name_plural': 'Market Arrival Data',
                'ordering': ['-report_period', 'origin_country'],
                'unique_together': {('country_code', 'report_period', 'origin_country')},
            },
        ),
    ]
