# Generated by Django 5.2.9 on 2026-02-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketKeyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('report_period', models.DateField(help_text='First day of reporting period (e.g., 2026-01-01)')),
                ('total_arrivals', models.PositiveIntegerField(default=0, help_text='Total tourist arrivals for the period')),
                ('occupancy_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Country-wide bed occupancy rate (%)', max_digits=5, null=True)),
                ('avg_stay_days', models.DecimalField(blank=True, decimal_places=2, help_text='Average duration of stay (days)', max_digits=5, null=True)),
                ('total_bed_nights', models.PositiveIntegerField(blank=True, help_text='Total tourist bed-nights', null=True)),
                ('total_beds_operational', models.PositiveIntegerField(blank=True, help_text='Total operational bed capacity', null=True)),
                ('source_report', models.CharField(blank=True, help_text='Source reference', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_records', to='platform_data.platformfileimport')),
            ],
            options={
                'verbose_name': 'Market Key Indicator',
                'verbose_name_plural': 'Market Key Indicators',
                'ordering': ['-report_period'],
                'unique_together': {('country_code', 'report_period')},
            },
        ),
    ]
