# Generated by Django 5.2.9 on 2026-02-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0002_marketkeyindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('report_period', models.DateField(help_text='First day of reporting period')),
                ('facility_type', models.CharField(choices=[('resorts', 'Resorts'), ('hotels', 'Hotels'), ('guesthouses', 'Guesthouses'), ('safari', 'Safari Vessels')], max_length=20)),
                ('arrivals', models.PositiveIntegerField(default=0)),
                ('share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_report', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_period', '-arrivals'],
                'unique_together': {('country_code', 'report_period', 'facility_type')},
            },
        ),
    ]
