# Generated by Django 5.0.1 on 2026-01-14 11:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., OTA, DIRECT, Agent', max_length=100)),
                ('base_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base channel discount from BAR (e.g., 15.00 for 15% off)', max_digits=5)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission the channel takes (for revenue analysis)', max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Hotel', help_text='Property name', max_length=200)),
                ('reference_base_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Reference rate for room index calculations (e.g., Standard Room rate)', max_digits=10)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol to display', max_length=5)),
            ],
            options={
                'verbose_name': 'Property Settings',
                'verbose_name_plural': 'Property Settings',
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Room Only, Bed & Breakfast', max_length=100)),
                ('meal_supplement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Meal cost per person in USD', max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Room, Deluxe Room, Suite', max_length=100)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base rate in USD (used directly or as reference for index/adjustment)', max_digits=10)),
                ('room_index', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for base rate (e.g., 1.0=same, 1.3=30% more, 2.0=double)', max_digits=5)),
                ('room_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount to add to base rate (alternative to room_index)', max_digits=10)),
                ('pricing_method', models.CharField(choices=[('direct', 'Direct Base Rate'), ('index', 'Index Multiplier'), ('adjustment', 'Fixed Adjustment')], default='direct', help_text='How to calculate room rate', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Low Season, High Season', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('season_index', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for base rates (e.g., 1.0, 1.3)', max_digits=4)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='RateModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Genius Member', 'Mobile App', 'Newsletter Subscriber'", max_length=100)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional discount % from channel base rate', max_digits=5)),
                ('active', models.BooleanField(default=True, help_text='Whether this rate modifier is currently available')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within channel')),
                ('modifier_type', models.CharField(choices=[('standard', 'Standard Rate'), ('member', 'Member/Loyalty Program'), ('mobile', 'Mobile App Exclusive'), ('promo', 'Promotional'), ('corporate', 'Corporate Rate'), ('last_minute', 'Last Minute Deal'), ('early_bird', 'Early Bird')], default='standard', help_text='Type of rate modifier', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Optional description (e.g., 'For Booking.com Genius Level 2 members')")),
                ('channel', models.ForeignKey(help_text='Which channel this modifier applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rate_modifiers', to='pricing.channel')),
            ],
            options={
                'verbose_name': 'Rate Modifier',
                'verbose_name_plural': 'Rate Modifiers',
                'ordering': ['channel', 'sort_order', 'name'],
                'unique_together': {('channel', 'name')},
            },
        ),
    ]
