# Generated by Django 5.0.1 on 2026-01-14 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='expected_occupancy',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Expected occupancy % for this season (e.g., 70.00 for 70%)', max_digits=5),
        ),
    ]
