# Generated by Django 5.2.9 on 2026-02-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.CharField(choices=[('peak', 'Peak Season'), ('shoulder', 'Shoulder Season'), ('low', 'Low Season')], max_length=10)),
                ('occupancy_band_label', models.CharField(max_length=50)),
                ('window_band_label', models.CharField(max_length=50)),
                ('current_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('suggested_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('direction', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('unchanged', 'No Change')], max_length=10)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('actual_adr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_occupancy_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('actual_revpar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('optimal_revpar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revpar_improvement_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('analysis_period_start', models.DateField(blank=True, null=True)),
                ('analysis_period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.dynamicpricingband')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dp_suggestions', to='pricing.property')),
                ('window_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.bookingwindowband')),
            ],
            options={
                'verbose_name': 'Dynamic Pricing Suggestion',
                'verbose_name_plural': 'Dynamic Pricing Suggestions',
                'ordering': ['-generated_at'],
            },
        ),
    ]
