# Generated by Django 5.2.9 on 2026-02-17 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_dynamicpricingsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='column_map_used',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileimport',
            name='import_type',
            field=models.CharField(default='reservation', max_length=30),
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'ABS PMS Weekly Export')", max_length=200)),
                ('import_type', models.CharField(choices=[('reservation', 'Reservations'), ('arrival_report', 'Country Arrival Report'), ('review', 'Guest Reviews'), ('competitor_rates', 'Competitor Rates')], default='reservation', max_length=30)),
                ('column_map', models.JSONField(default=dict, help_text='Maps system DB fields to CSV column headers')),
                ('value_transforms', models.JSONField(blank=True, default=dict, help_text='Value transformations per field')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Import settings: header_row, date_format, skip_rows, encoding, etc.')),
                ('source_headers', models.JSONField(blank=True, default=list, help_text='Original CSV headers this template maps from')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-use this template when headers match')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='Property this template belongs to (null = org-level shared)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to='pricing.property')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization for shared templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to='pricing.organization')),
            ],
            options={
                'verbose_name': 'Import Template',
                'verbose_name_plural': 'Import Templates',
                'ordering': ['-last_used_at', '-use_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fileimport',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Import template used for column mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_imports', to='pricing.importtemplate'),
        ),
    ]
