# Generated by Django 5.0.1 on 2026-01-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_season_expected_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=10, help_text='Number of rooms of this type in the property'),
        ),
    ]
