# Generated by Django 5.0.1 on 2026-01-15 05:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_roomtype_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='pricing_method',
            field=models.CharField(choices=[('direct', 'Direct Base Rate'), ('index', 'Index Multiplier'), ('adjustment', 'Fixed Adjustment')], default='index', help_text='How to calculate room rate', max_length=20),
        ),
        migrations.CreateModel(
            name='SeasonModifierOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Season-specific discount % (overrides base modifier discount)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Optional notes explaining why this override exists')),
                ('modifier', models.ForeignKey(help_text='Which modifier this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='season_overrides', to='pricing.ratemodifier')),
                ('season', models.ForeignKey(help_text='Which season this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='modifier_overrides', to='pricing.season')),
            ],
            options={
                'verbose_name': 'Season Modifier Override',
                'verbose_name_plural': 'Season Modifier Overrides',
                'ordering': ['modifier', 'season'],
                'unique_together': {('modifier', 'season')},
            },
        ),
    ]
