# Generated by Django 5.2.9 on 2026-02-19 19:18

import django.db.models.deletion
import pricing.models.pricing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_fileimport_column_map_used_fileimport_import_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(default=pricing.models.pricing.generate_agent_token, editable=False, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, help_text="Channel with this agent's rates. Leave blank for default agent channel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_agents', to='pricing.channel')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agents', to='pricing.property')),
            ],
            options={
                'ordering': ['property', 'name'],
            },
        ),
    ]
