# Generated by Django 6.0.2 on 2026-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_travelagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country_code',
            field=models.CharField(db_index=True, default='MV', help_text="ISO 3166-1 alpha-2 country code (e.g., 'MV' for Maldives)", max_length=2),
        ),
    ]
