# Generated by Django 5.0.1 on 2026-01-15 06:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_roomtype_pricing_method_seasonmodifieroverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonmodifieroverride',
            options={'ordering': ['season', 'modifier__channel', 'modifier__sort_order'], 'verbose_name': 'Season Modifier Discount', 'verbose_name_plural': 'Season Modifier Discounts'},
        ),
        migrations.AddField(
            model_name='seasonmodifieroverride',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='True if manually edited, False if using base default'),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount % for this modifier in this season', max_digits=5),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='modifier',
            field=models.ForeignKey(help_text='Which modifier this applies to', on_delete=django.db.models.deletion.CASCADE, related_name='season_discounts', to='pricing.ratemodifier'),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes explaining customization'),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='season',
            field=models.ForeignKey(help_text='Which season this applies to', on_delete=django.db.models.deletion.CASCADE, related_name='modifier_discounts', to='pricing.season'),
        ),
    ]
