# Generated by Django 5.2.9 on 2026-02-28 00:13

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_property_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_avg_bb', models.DecimalField(blank=True, decimal_places=2, help_text='Market average BB rate (auto-calculated)', max_digits=10, null=True)),
                ('market_median_bb', models.DecimalField(blank=True, decimal_places=2, help_text='Market median BB rate (auto-calculated)', max_digits=10, null=True)),
                ('market_min_bb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_max_bb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('competitor_count', models.PositiveIntegerField(default=0)),
                ('strategy', models.CharField(choices=[('undercut', 'Undercut (below market avg)'), ('match', 'Match (at market avg)'), ('mid_premium', 'Mid-Premium (+10-20% above avg)'), ('premium', 'Premium (+20-40% above avg)')], default='mid_premium', help_text='Your positioning strategy relative to market', max_length=20)),
                ('bb_floor', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum BB rate — never sell below this ($)', max_digits=10)),
                ('bb_ceiling', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Maximum BB rate for this market ($)', max_digits=10)),
                ('hb_supplement', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='HB supplement added to BB rate (total for default occupancy)', max_digits=10)),
                ('fb_supplement', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='FB supplement added to BB rate (total for default occupancy)', max_digits=10)),
                ('last_survey_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(help_text='Property this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='market_position', to='pricing.property')),
            ],
            options={
                'verbose_name': 'Market Position',
                'verbose_name_plural': 'Market Positions',
            },
        ),
        migrations.CreateModel(
            name='CompetitiveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(help_text='Competitor property name', max_length=200)),
                ('bb_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Bed & Breakfast rate ($)', max_digits=10, null=True)),
                ('hb_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Half Board rate ($)', max_digits=10, null=True)),
                ('fb_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Full Board rate ($)', max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Guest rating (e.g. 9.2)', max_digits=3, null=True)),
                ('total_rooms', models.PositiveIntegerField(default=0, help_text='Number of rooms')),
                ('position', models.CharField(choices=[('luxury', 'Luxury'), ('premium', 'Premium'), ('mid', 'Mid-Range'), ('budget', 'Budget')], default='mid', help_text='Market positioning tier', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Differentiators, amenities, location notes')),
                ('source', models.CharField(default='Booking.com', help_text='Where the rate was observed', max_length=100)),
                ('surveyed_date', models.DateField(default=datetime.date.today, help_text='When rates were last checked')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Your property this competitor is benchmarked against', on_delete=django.db.models.deletion.CASCADE, related_name='competitive_set', to='pricing.property')),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitive Set',
                'ordering': ['hotel', '-bb_rate'],
                'unique_together': {('hotel', 'competitor_name')},
            },
        ),
    ]
