# Generated by Django 5.0.1 on 2026-01-15 20:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_seasonmodifieroverride_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='distribution_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected % of bookings from this channel (for revenue forecasting)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
