# Generated by Django 5.2.9 on 2026-03-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_marketposition_competitiveset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('manager', 'Manager'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='pricing.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Organization Role',
                'verbose_name_plural': 'User Organization Roles',
                'ordering': ['organization', 'user'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
