# Generated by Django 5.0.1 on 2026-01-19 12:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_channel_distribution_share_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPickupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, help_text='Date when this OTB position was recorded')),
                ('arrival_date', models.DateField(db_index=True, help_text='The future arrival date being tracked')),
                ('days_out', models.PositiveIntegerField(help_text='Days between snapshot_date and arrival_date')),
                ('otb_room_nights', models.PositiveIntegerField(default=0, help_text='Total room nights booked for this arrival date')),
                ('otb_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue booked for this arrival date', max_digits=12)),
                ('otb_reservations', models.PositiveIntegerField(default=0, help_text='Number of reservations for this arrival date')),
                ('otb_by_channel', models.JSONField(blank=True, default=dict, help_text="Room nights breakdown by channel: {'OTA': 15, 'DIRECT': 8}")),
                ('otb_by_room_type', models.JSONField(blank=True, default=dict, help_text='Room nights breakdown by room type')),
                ('otb_by_rate_plan', models.JSONField(blank=True, default=dict, help_text='Room nights breakdown by rate plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Pickup Snapshot',
                'verbose_name_plural': 'Daily Pickup Snapshots',
                'ordering': ['-snapshot_date', 'arrival_date'],
                'indexes': [models.Index(fields=['arrival_date', 'days_out'], name='pricing_dai_arrival_3cac0e_idx'), models.Index(fields=['snapshot_date'], name='pricing_dai_snapsho_2e67f7_idx'), models.Index(fields=['arrival_date', 'snapshot_date'], name='pricing_dai_arrival_67d3d6_idx')],
                'unique_together': {('snapshot_date', 'arrival_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPickupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, help_text='Date when this snapshot was recorded')),
                ('target_month', models.DateField(db_index=True, help_text='First day of the target month (e.g., 2026-03-01 for March 2026)')),
                ('days_out', models.PositiveIntegerField(help_text='Days between snapshot_date and start of target_month')),
                ('otb_room_nights', models.PositiveIntegerField(default=0, help_text='Total room nights booked for this month')),
                ('otb_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue booked for this month', max_digits=12)),
                ('otb_reservations', models.PositiveIntegerField(default=0, help_text='Number of reservations for this month')),
                ('otb_occupancy_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='OTB occupancy percentage', max_digits=5)),
                ('available_room_nights', models.PositiveIntegerField(default=0, help_text='Total available room nights for this month')),
                ('otb_by_channel', models.JSONField(blank=True, default=dict, help_text='Room nights by channel')),
                ('otb_by_room_type', models.JSONField(blank=True, default=dict, help_text='Room nights by room type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Pickup Snapshot',
                'verbose_name_plural': 'Monthly Pickup Snapshots',
                'ordering': ['-snapshot_date', 'target_month'],
                'indexes': [models.Index(fields=['target_month', 'days_out'], name='pricing_mon_target__e8e082_idx'), models.Index(fields=['target_month', 'snapshot_date'], name='pricing_mon_target__ae2fd3_idx')],
                'unique_together': {('snapshot_date', 'target_month')},
            },
        ),
        migrations.CreateModel(
            name='OccupancyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(db_index=True, help_text='First day of the target month')),
                ('forecast_date', models.DateField(db_index=True, help_text='Date when this forecast was generated')),
                ('days_out', models.PositiveIntegerField(help_text='Days between forecast_date and start of target_month')),
                ('available_room_nights', models.PositiveIntegerField(default=0, help_text='Total available room nights for this month')),
                ('otb_room_nights', models.PositiveIntegerField(default=0, help_text='Room nights currently on the books')),
                ('otb_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue currently on the books', max_digits=12)),
                ('otb_occupancy_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current OTB occupancy percentage', max_digits=5)),
                ('pickup_forecast_nights', models.PositiveIntegerField(default=0, help_text='Forecasted total room nights (OTB + expected pickup)')),
                ('pickup_forecast_occupancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecasted occupancy percentage', max_digits=5)),
                ('pickup_forecast_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecasted gross revenue', max_digits=12)),
                ('pickup_expected_additional', models.PositiveIntegerField(default=0, help_text='Expected additional room nights to be picked up')),
                ('forecast_from_curve', models.PositiveIntegerField(default=0, help_text='Room nights forecast from pickup curve (50% weight)')),
                ('forecast_from_stly', models.PositiveIntegerField(default=0, help_text='Room nights forecast from STLY comparison (30% weight)')),
                ('forecast_from_velocity', models.PositiveIntegerField(default=0, help_text='Room nights forecast from recent velocity (20% weight)')),
                ('confidence_level', models.CharField(choices=[('very_low', 'Very Low (< 30 days data)'), ('low', 'Low (30-60 days data)'), ('medium', 'Medium (60-90 days data)'), ('high', 'High (90+ days data)')], default='medium', help_text='Confidence level based on data availability', max_length=20)),
                ('confidence_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Confidence percentage (25-95%)', max_digits=5)),
                ('scenario_occupancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual scenario occupancy (from Season.expected_occupancy)', max_digits=5)),
                ('scenario_room_nights', models.PositiveIntegerField(default=0, help_text='Room nights based on scenario occupancy')),
                ('scenario_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue based on scenario occupancy', max_digits=12)),
                ('variance_nights', models.IntegerField(default=0, help_text='Pickup forecast - Scenario (can be negative)')),
                ('variance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage difference from scenario', max_digits=6)),
                ('stly_occupancy', models.DecimalField(blank=True, decimal_places=2, help_text='STLY final occupancy (if available)', max_digits=5, null=True)),
                ('stly_otb_at_same_point', models.PositiveIntegerField(blank=True, help_text='STLY OTB at same days_out', null=True)),
                ('vs_stly_pace_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage ahead/behind STLY pace', max_digits=6, null=True)),
                ('forecast_adr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecasted ADR', max_digits=10)),
                ('forecast_revpar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecasted RevPAR', max_digits=10)),
                ('forecast_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecasted commission (based on channel mix)', max_digits=12)),
                ('forecast_net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecasted net revenue after commission', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Auto-generated insights or manual notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, help_text='Season this month falls into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='pricing.season')),
            ],
            options={
                'verbose_name': 'Occupancy Forecast',
                'verbose_name_plural': 'Occupancy Forecasts',
                'ordering': ['target_month', '-forecast_date'],
                'indexes': [models.Index(fields=['target_month', 'days_out'], name='pricing_occ_target__cb0856_idx'), models.Index(fields=['forecast_date'], name='pricing_occ_forecas_5e4496_idx')],
                'unique_together': {('target_month', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='PickupCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.CharField(choices=[('peak', 'Peak Season'), ('high', 'High Season'), ('shoulder', 'Shoulder Season'), ('low', 'Low Season')], db_index=True, help_text='Season type this curve applies to', max_length=20)),
                ('days_out', models.PositiveIntegerField(help_text='Days before arrival date')),
                ('cumulative_percent', models.DecimalField(decimal_places=2, help_text='Percentage of final occupancy typically booked at this days_out', max_digits=5)),
                ('sample_size', models.PositiveIntegerField(default=0, help_text='Number of historical periods used to build this data point')),
                ('std_deviation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard deviation of the cumulative_percent', max_digits=5)),
                ('curve_version', models.PositiveIntegerField(default=1, help_text='Version number for tracking curve updates')),
                ('built_from_start', models.DateField(blank=True, help_text='Start date of historical data used to build curve', null=True)),
                ('built_from_end', models.DateField(blank=True, help_text='End date of historical data used to build curve', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, help_text='Specific season (optional - if null, applies to all seasons of this type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_curves', to='pricing.season')),
            ],
            options={
                'verbose_name': 'Pickup Curve',
                'verbose_name_plural': 'Pickup Curves',
                'ordering': ['season_type', '-days_out'],
                'indexes': [models.Index(fields=['season_type', 'days_out'], name='pricing_pic_season__931f4d_idx')],
                'unique_together': {('season_type', 'season', 'days_out', 'curve_version')},
            },
        ),
    ]
