# Generated by Django 5.0.1 on 2026-01-19 13:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_dailypickupsnapshot_monthlypickupsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash for duplicate detection', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error messages with row numbers')),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File Import',
                'verbose_name_plural': 'File Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Booking.com', 'Direct - Walk-in')", max_length=100, unique=True)),
                ('import_values', models.JSONField(default=list, help_text="List of values to match from import (e.g., ['Booking.com', 'booking.com'])")),
                ('is_direct', models.BooleanField(default=False, help_text='Is this a direct booking source?')),
                ('user_mappings', models.JSONField(blank=True, default=list, help_text="User names that indicate this source when Source is empty (e.g., ['Reekko', 'Maais'])")),
                ('commission_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override commission % (if different from channel)', max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Map to existing channel for analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_sources', to='pricing.channel')),
            ],
            options={
                'verbose_name': 'Booking Source',
                'verbose_name_plural': 'Booking Sources',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Guest name from reservation', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Guest email (if available)', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Guest phone (if available)', max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Guest country from reservation', max_length=100)),
                ('booking_count', models.PositiveIntegerField(default=0, help_text='Total number of bookings')),
                ('total_nights', models.PositiveIntegerField(default=0, help_text='Total room nights stayed')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime revenue from this guest', max_digits=12)),
                ('first_booking_date', models.DateField(blank=True, help_text='Date of first booking', null=True)),
                ('last_booking_date', models.DateField(blank=True, help_text='Date of most recent booking', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['-last_booking_date', 'name'],
                'indexes': [models.Index(fields=['name', 'country'], name='pricing_gue_name_67a856_idx'), models.Index(fields=['booking_count'], name='pricing_gue_booking_af160b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_no', models.CharField(db_index=True, help_text='Confirmation number (base number, without room suffix)', max_length=50)),
                ('original_confirmation_no', models.CharField(blank=True, help_text='Original confirmation number from import (e.g., 286-1)', max_length=50)),
                ('booking_date', models.DateField(db_index=True, help_text='Date when booking was made')),
                ('arrival_date', models.DateField(db_index=True, help_text='Check-in date')),
                ('departure_date', models.DateField(help_text='Check-out date')),
                ('nights', models.PositiveIntegerField(default=1, help_text='Number of nights')),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('lead_time_days', models.IntegerField(db_index=True, default=0, help_text='Days between booking and arrival (arrival - booking)')),
                ('room_type_name', models.CharField(blank=True, help_text='Original room type name from import', max_length=100)),
                ('rate_plan_name', models.CharField(blank=True, help_text='Original rate plan name from import', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total booking amount', max_digits=12)),
                ('adr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average Daily Rate (total / nights)', max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20)),
                ('room_sequence', models.PositiveSmallIntegerField(default=1, help_text='Room sequence in multi-room booking (1, 2, 3...)')),
                ('is_multi_room', models.BooleanField(default=False, help_text='Is this part of a multi-room booking?')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original row data from import')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_source', models.ForeignKey(blank=True, help_text='Booking source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.bookingsource')),
                ('channel', models.ForeignKey(blank=True, help_text='Channel (from booking source)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.channel')),
                ('file_import', models.ForeignKey(blank=True, help_text='Import batch this came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.fileimport')),
                ('guest', models.ForeignKey(blank=True, help_text='Guest record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.guest')),
                ('parent_reservation', models.ForeignKey(blank=True, help_text='Parent reservation for multi-room bookings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rooms', to='pricing.reservation')),
                ('rate_plan', models.ForeignKey(blank=True, help_text='Rate plan / meal plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.rateplan')),
                ('room_type', models.ForeignKey(blank=True, help_text='Room type booked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.roomtype')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-booking_date', '-arrival_date'],
                'indexes': [models.Index(fields=['arrival_date', 'status'], name='pricing_res_arrival_410a42_idx'), models.Index(fields=['booking_date', 'arrival_date'], name='pricing_res_booking_797871_idx'), models.Index(fields=['lead_time_days'], name='pricing_res_lead_ti_9e1b8f_idx'), models.Index(fields=['confirmation_no', 'room_sequence'], name='pricing_res_confirm_a0da07_idx')],
                'unique_together': {('confirmation_no', 'room_sequence')},
            },
        ),
    ]
