# Generated by Django 5.2.9 on 2026-03-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_userorganizationrole'),
    ]

    operations = [
        # Remove template FK from PropertyModifier first (before deleting ModifierTemplate)
        migrations.RemoveField(
            model_name='propertymodifier',
            name='template',
        ),
        # Delete all dead models (Django handles their fields/indexes automatically)
        migrations.DeleteModel(
            name='DailyPickupSnapshot',
        ),
        migrations.DeleteModel(
            name='DynamicPricingSuggestion',
        ),
        migrations.DeleteModel(
            name='MonthlyPickupSnapshot',
        ),
        migrations.DeleteModel(
            name='OccupancyForecast',
        ),
        migrations.DeleteModel(
            name='PickupCurve',
        ),
        migrations.DeleteModel(
            name='ModifierTemplate',
        ),
    ]
