# Generated by Django 5.2.9 on 2026-03-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_remove_dead_models_phase1b'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertymodifier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='propertymodifier',
            name='version',
            field=models.ForeignKey(blank=True, help_text='Pricing version (null = global / unversioned)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_modifiers', to='pricing.pricingmatrixversion'),
        ),
        migrations.AlterUniqueTogether(
            name='propertymodifier',
            unique_together={('hotel', 'code', 'version')},
        ),
    ]
