# Generated by Django 5.0.1 on 2026-01-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_fileimport_bookingsource_guest_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_date',
            field=models.DateField(blank=True, help_text='Date when reservation was cancelled', null=True),
        ),
    ]
