# Generated by Django 5.0.1 on 2026-01-20 09:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '009_add_multi_org_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ratemodifier',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rateplan',
            name='property',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='property',
        ),
        migrations.RemoveField(
            model_name='season',
            name='property',
        ),
       
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.SlugField(help_text="URL-friendly code (e.g., 'atoll-resorts')", unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol for display', max_length=5),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_currency',
            field=models.CharField(default='USD', help_text='Default currency code (e.g., USD, EUR)', max_length=3),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this organization is active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text="Organization name (e.g., 'Atoll Resorts Group')", max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.SlugField(help_text="URL-friendly code (e.g., 'biosphere-inn')"),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol to display', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this property is active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Maldives, Kaafu Atoll', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='My Hotel', help_text='Property name', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(help_text='Parent organization', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='pricing.organization'),
        ),
        migrations.AlterField(
            model_name='property',
            name='reference_base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Reference rate for room index calculations (e.g., Standard Room rate)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, help_text='Total number of rooms (auto-calculated from room types)'),
        ),
    ]
