# Generated by Django 5.2.9 on 2026-03-25 06:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_add_version_to_propertymodifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LengthOfStayTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Short Stay Premium', '7+ Night Discount'", max_length=100)),
                ('min_nights', models.PositiveIntegerField(help_text='Minimum nights (inclusive)')),
                ('max_nights', models.PositiveIntegerField(blank=True, help_text='Maximum nights (inclusive, null = no limit)', null=True)),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount (% off)'), ('premium', 'Premium (% surcharge)')], default='discount', max_length=10)),
                ('adjustment_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage adjustment (e.g., 10 = 10% off or 10% surcharge)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='los_tiers', to='pricing.property')),
                ('room_type', models.ForeignKey(blank=True, help_text='Apply to specific room type only (null = all)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.roomtype')),
                ('season', models.ForeignKey(blank=True, help_text='Apply to specific season only (null = all)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.season')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='los_tiers', to='pricing.pricingmatrixversion')),
            ],
            options={
                'ordering': ['hotel', 'sort_order', 'min_nights'],
            },
        ),
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('segment_type', models.CharField(choices=[('leisure', 'Leisure'), ('corporate', 'Corporate'), ('group', 'Group/MICE'), ('government', 'Government'), ('crew', 'Airline Crew'), ('wholesale', 'Wholesale/Tour'), ('other', 'Other')], default='leisure', max_length=20)),
                ('rate_sensitivity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='How price-sensitive this segment is', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_segments', to='pricing.property')),
                ('primary_channel', models.ForeignKey(blank=True, help_text='Primary booking channel for this segment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.channel')),
            ],
            options={
                'ordering': ['hotel', 'sort_order', 'name'],
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GroupAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_code', models.SlugField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('rooms_blocked', models.PositiveIntegerField(help_text='Total rooms allocated to this group')),
                ('rooms_picked_up', models.PositiveIntegerField(default=0, help_text='Rooms confirmed/used from allotment')),
                ('agreed_rate', models.DecimalField(decimal_places=2, help_text='Negotiated group rate per room per night', max_digits=10)),
                ('release_date', models.DateField(help_text='Date after which unbooked rooms are released back to inventory')),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='tentative', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.travelagent')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_allotments', to='pricing.property')),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.rateplan')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.marketsegment')),
            ],
            options={
                'ordering': ['hotel', 'arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('revenue_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target total revenue for the month', max_digits=12)),
                ('occupancy_target', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Target occupancy percentage', max_digits=5)),
                ('adr_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target Average Daily Rate', max_digits=10)),
                ('revpar_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target Revenue Per Available Room', max_digits=10)),
                ('segment_targets', models.JSONField(blank=True, default=dict, help_text='Per-segment targets: {segment_id: {revenue: X, rooms: Y}}')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='pricing.property')),
            ],
            options={
                'ordering': ['hotel', 'year', 'month'],
                'unique_together': {('hotel', 'year', 'month')},
            },
        ),
    ]
