# Generated by Django 5.0.1 on 2026-01-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_remove_channel_property_remove_organization_logo_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='pricing.property'),
        ),
    ]
