# Generated by Django 5.2.9 on 2026-03-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_add_revenue_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_category',
            field=models.CharField(blank=True, choices=[('change_of_plans', 'Change of Plans'), ('found_better_rate', 'Found Better Rate'), ('found_alternative', 'Found Alternative Property'), ('booking_error', 'Booking Error / Duplicate'), ('travel_restrictions', 'Travel Restrictions'), ('personal', 'Personal Reasons'), ('weather', 'Weather Concerns'), ('no_response', 'No Response / Ghost'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for cancellation (from PMS or manual entry)', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_revenue_estimated',
            field=models.BooleanField(default=False, help_text='True if total_amount was estimated (not from PMS)'),
        ),
    ]
