# Generated by Django 5.0.1 on 2026-01-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_reservation_cancellation_date_roomtype_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='pricing.property'),
        ),
      
        migrations.AddField(
            model_name='season',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='pricing.property'),
        ),
    ]
