# Generated by Django 5.2.9 on 2026-03-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_add_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganizationrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Revenue Manager'), ('sales', 'Sales / Distribution'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_mappings', to='pricing.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.roomtype')),
            ],
            options={
                'verbose_name': 'Room Type Mapping',
                'verbose_name_plural': 'Room Type Mappings',
                'unique_together': {('hotel', 'import_name')},
            },
        ),
    ]
