# Generated by Django 5.0.1 on 2026-01-20 12:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_channel_property_reservation_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupancyforecast',
            options={'ordering': ['hotel', 'target_month', '-forecast_date'], 'verbose_name': 'Occupancy Forecast', 'verbose_name_plural': 'Occupancy Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='pickupcurve',
            options={'ordering': ['hotel', 'season_type', '-days_out'], 'verbose_name': 'Pickup Curve', 'verbose_name_plural': 'Pickup Curves'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['hotel', 'sort_order', 'name'], 'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['hotel', 'start_date'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='seasonmodifieroverride',
            options={'ordering': ['season', 'modifier__channel', 'modifier__sort_order'], 'verbose_name': 'Season Modifier Override', 'verbose_name_plural': 'Season Modifier Overrides'},
        ),
        migrations.RemoveIndex(
            model_name='dailypickupsnapshot',
            name='pricing_dai_arrival_3cac0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailypickupsnapshot',
            name='pricing_dai_snapsho_2e67f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailypickupsnapshot',
            name='pricing_dai_arrival_67d3d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlypickupsnapshot',
            name='pricing_mon_target__e8e082_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlypickupsnapshot',
            name='pricing_mon_target__ae2fd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='occupancyforecast',
            name='pricing_occ_target__cb0856_idx',
        ),
        migrations.RemoveIndex(
            model_name='occupancyforecast',
            name='pricing_occ_forecas_5e4496_idx',
        ),
        migrations.RemoveIndex(
            model_name='pickupcurve',
            name='pricing_pic_season__931f4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='pricing_res_arrival_410a42_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='pricing_res_booking_797871_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailypickupsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypickupsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='occupancyforecast',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pickupcurve',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='property',
        ),
        migrations.RemoveField(
            model_name='season',
            name='property',
        ),
        migrations.AddField(
            model_name='dailypickupsnapshot',
            name='hotel',
            field=models.ForeignKey(default=1, help_text='Property this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='pricing.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileimport',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Property this import belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_imports', to='pricing.property'),
        ),
        migrations.AddField(
            model_name='monthlypickupsnapshot',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='pricing.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupancyforecast',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='pricing.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickupcurve',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_curves', to='pricing.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Property this reservation is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='pricing.property'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(default=1, help_text='Property this room type belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='pricing.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='hotel',
            field=models.ForeignKey(default=1, help_text='Property this season belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='pricing.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingsource',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_sources', to='pricing.channel'),
        ),
        migrations.AlterField(
            model_name='bookingsource',
            name='commission_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsource',
            name='import_values',
            field=models.JSONField(default=list, help_text='Values to match from import files'),
        ),
        migrations.AlterField(
            model_name='bookingsource',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingsource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingsource',
            name='user_mappings',
            field=models.JSONField(blank=True, default=list, help_text='User names for empty source handling'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='base_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base channel discount from BAR', max_digits=5),
        ),
        migrations.AlterField(
            model_name='channel',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission the channel takes', max_digits=5),
        ),
        migrations.AlterField(
            model_name='channel',
            name='distribution_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected % of bookings from this channel', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='arrival_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='days_out',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='otb_by_channel',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='otb_by_rate_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='otb_by_room_type',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='otb_reservations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='otb_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='otb_room_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailypickupsnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guest',
            name='booking_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='total_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='available_room_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='days_out',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='otb_by_channel',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='otb_by_room_type',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='otb_occupancy_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='otb_reservations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='otb_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='otb_room_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='monthlypickupsnapshot',
            name='target_month',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='available_room_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='confidence_level',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='confidence_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='days_out',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_adr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_from_curve',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_from_stly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_from_velocity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_net_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='forecast_revpar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='otb_occupancy_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='otb_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='otb_room_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='pickup_expected_additional',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='pickup_forecast_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='pickup_forecast_occupancy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='pickup_forecast_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='scenario_occupancy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='scenario_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='scenario_room_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='pricing.season'),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='stly_occupancy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='stly_otb_at_same_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='target_month',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='variance_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='variance_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='occupancyforecast',
            name='vs_stly_pace_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='built_from_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='built_from_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='cumulative_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='curve_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='days_out',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='sample_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_curves', to='pricing.season'),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='season_type',
            field=models.CharField(choices=[('peak', 'Peak Season'), ('high', 'High Season'), ('shoulder', 'Shoulder Season'), ('low', 'Low Season')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pickupcurve',
            name='std_deviation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='ratemodifier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ratemodifier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ratemodifier',
            name='modifier_type',
            field=models.CharField(choices=[('standard', 'Standard Rate'), ('member', 'Member/Loyalty Program'), ('mobile', 'Mobile App Exclusive'), ('promo', 'Promotional'), ('corporate', 'Corporate Rate'), ('last_minute', 'Last Minute Deal'), ('early_bird', 'Early Bird')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='ratemodifier',
            name='name',
            field=models.CharField(help_text="e.g., 'Genius Member', 'Mobile App'", max_length=100),
        ),
        migrations.AlterField(
            model_name='ratemodifier',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='adr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrival_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.bookingsource'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.channel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='file_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.fileimport'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_multi_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lead_time_days',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='original_confirmation_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parent_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rooms', to='pricing.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rate_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.rateplan'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rate_plan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_sequence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pricing.roomtype'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, help_text='Base rate in USD (used directly or as reference)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=10, help_text='Number of rooms of this type'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount to add to property reference rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_index',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for property reference rate', max_digits=5),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_discounts', to='pricing.ratemodifier'),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seasonmodifieroverride',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_discounts', to='pricing.season'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypickupsnapshot',
            unique_together={('hotel', 'snapshot_date', 'arrival_date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlypickupsnapshot',
            unique_together={('hotel', 'snapshot_date', 'target_month')},
        ),
        migrations.AlterUniqueTogether(
            name='occupancyforecast',
            unique_together={('hotel', 'target_month', 'forecast_date')},
        ),
        migrations.AlterUniqueTogether(
            name='pickupcurve',
            unique_together={('hotel', 'season_type', 'season', 'days_out', 'curve_version')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('hotel', 'confirmation_no', 'room_sequence')},
        ),
        migrations.AddIndex(
            model_name='dailypickupsnapshot',
            index=models.Index(fields=['hotel', 'arrival_date', 'days_out'], name='pricing_dai_hotel_i_54e746_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypickupsnapshot',
            index=models.Index(fields=['hotel', 'snapshot_date'], name='pricing_dai_hotel_i_602508_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypickupsnapshot',
            index=models.Index(fields=['hotel', 'target_month', 'days_out'], name='pricing_mon_hotel_i_aa930b_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancyforecast',
            index=models.Index(fields=['hotel', 'target_month', 'days_out'], name='pricing_occ_hotel_i_d5c2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupcurve',
            index=models.Index(fields=['hotel', 'season_type', 'days_out'], name='pricing_pic_hotel_i_e53f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'arrival_date', 'status'], name='pricing_res_hotel_i_6a1dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'booking_date', 'arrival_date'], name='pricing_res_hotel_i_434155_idx'),
        ),
    ]
