# Generated by Django 5.0.1 on 2026-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_alter_occupancyforecast_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('hotel', 'confirmation_no', 'arrival_date', 'room_sequence')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
