# Generated by Django 5.0.1 on 2026-02-01 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'New Year Premium', 'Eid Discount')", max_length=100)),
                ('override_type', models.CharField(choices=[('amount', 'Fixed Amount ($)'), ('percentage', 'Percentage (%)')], default='amount', help_text='How to apply the adjustment', max_length=20)),
                ('adjustment', models.DecimalField(decimal_places=2, help_text='Adjustment value. Positive = increase, Negative = decrease. For amount: dollars (e.g., 50 or -20). For percentage: percent (e.g., 10 for +10%, -15 for -15%)', max_digits=10)),
                ('priority', models.PositiveIntegerField(default=50, help_text='Priority 1-100. Higher priority wins when multiple overrides apply to the same date. (e.g., 90 = high priority)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True, help_text='Whether this override is currently active')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Property this override belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='date_rate_overrides', to='pricing.property')),
            ],
            options={
                'verbose_name': 'Date Rate Override',
                'verbose_name_plural': 'Date Rate Overrides',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DateRateOverridePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date (inclusive)')),
                ('end_date', models.DateField(help_text='End date (inclusive). Same as start for single day.')),
                ('override', models.ForeignKey(help_text='Parent override', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='pricing.daterateoverride')),
            ],
            options={
                'verbose_name': 'Override Period',
                'verbose_name_plural': 'Override Periods',
                'ordering': ['start_date'],
            },
        ),
    ]
