# Generated by Django 5.0.1 on 2026-02-04 11:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.db.models import F

def create_default_templates(apps, schema_editor):
    """Create default modifier templates for existing organizations."""
    Organization = apps.get_model('pricing', 'Organization')
    ModifierTemplate = apps.get_model('pricing', 'ModifierTemplate')
    
    default_templates = [
        {
            'name': 'Season Index',
            'code': 'season-index',
            'description': 'Seasonal pricing adjustment',
            'modifier_type': 'index',
            'applies_to': 'season',
            'default_value': Decimal('1.00'),
            'stack_order': 10,
        },
        {
            'name': 'Room Type Index',
            'code': 'room-type-index',
            'description': 'Room category pricing adjustment',
            'modifier_type': 'index',
            'applies_to': 'room_type',
            'default_value': Decimal('1.00'),
            'stack_order': 20,
        },
        {
            'name': 'Channel Discount',
            'code': 'channel-discount',
            'description': 'Distribution channel discount',
            'modifier_type': 'discount',
            'applies_to': 'channel',
            'default_value': Decimal('0.00'),
            'stack_order': 30,
        },
        {
            'name': 'Member Discount',
            'code': 'member-discount',
            'description': 'Loyalty/member program discount',
            'modifier_type': 'discount',
            'applies_to': 'guest_type',
            'default_value': Decimal('0.00'),
            'stack_order': 40,
        },
        {
            'name': 'Promotional Discount',
            'code': 'promo-discount',
            'description': 'Promotional offer discount',
            'modifier_type': 'discount',
            'applies_to': 'promo',
            'default_value': Decimal('0.00'),
            'stack_order': 50,
        },
        {
            'name': 'Length of Stay Discount',
            'code': 'los-discount',
            'description': 'Discount based on number of nights',
            'modifier_type': 'discount',
            'applies_to': 'los',
            'default_value': Decimal('0.00'),
            'stack_order': 60,
        },
        {
            'name': 'Early Bird Discount',
            'code': 'early-bird',
            'description': 'Discount for advance bookings',
            'modifier_type': 'discount',
            'applies_to': 'booking_window',
            'default_value': Decimal('0.00'),
            'stack_order': 70,
        },
        {
            'name': 'Last Minute Surcharge',
            'code': 'last-minute',
            'description': 'Surcharge for last-minute bookings',
            'modifier_type': 'surcharge',
            'applies_to': 'booking_window',
            'default_value': Decimal('0.00'),
            'stack_order': 80,
        },
    ]
    
    for org in Organization.objects.all():
        for template_data in default_templates:
            ModifierTemplate.objects.get_or_create(
                organization=org,
                code=template_data['code'],
                defaults=template_data
            )


def migrate_existing_data(apps, schema_editor):
    """
    Migrate existing Season, Channel, and RateModifier data to PropertyModifier.
    """
    Property = apps.get_model('pricing', 'Property')
    Season = apps.get_model('pricing', 'Season')
    Channel = apps.get_model('pricing', 'Channel')
    RateModifier = apps.get_model('pricing', 'RateModifier')
    ModifierTemplate = apps.get_model('pricing', 'ModifierTemplate')
    PropertyModifier = apps.get_model('pricing', 'PropertyModifier')
    
    for hotel in Property.objects.all():
        org = hotel.organization
        
        # Get templates
        season_template = ModifierTemplate.objects.filter(
            organization=org, code='season-index'
        ).first()
        channel_template = ModifierTemplate.objects.filter(
            organization=org, code='channel-discount'
        ).first()
        member_template = ModifierTemplate.objects.filter(
            organization=org, code='member-discount'
        ).first()
        
        # Migrate Season indexes
        for season in Season.objects.filter(hotel=hotel):
            code = f"season-{season.id}"
            PropertyModifier.objects.get_or_create(
                hotel=hotel,
                code=code,
                defaults={
                    'template': season_template,
                    'name': season.name,
                    'modifier_type': 'index',
                    'applies_to': 'season',
                    'value': season.season_index,
                    'stack_order': 10,
                    'season': season,
                    'is_active': True,
                }
            )
        
        # Migrate Channel discounts
        for channel in Channel.objects.all():
            if channel.base_discount_percent > 0:
                code = f"channel-{channel.id}"
                PropertyModifier.objects.get_or_create(
                    hotel=hotel,
                    code=code,
                    defaults={
                        'template': channel_template,
                        'name': f"{channel.name} Discount",
                        'modifier_type': 'discount',
                        'applies_to': 'channel',
                        'value': channel.base_discount_percent,
                        'stack_order': 30,
                        'channel': channel,
                        'is_active': True,
                    }
                )
        
        # Migrate RateModifiers (Genius, Mobile, etc.)
        for rate_modifier in RateModifier.objects.filter(active=True):
            if rate_modifier.discount_percent > 0:
                code = f"modifier-{rate_modifier.id}"
                PropertyModifier.objects.get_or_create(
                    hotel=hotel,
                    code=code,
                    defaults={
                        'template': member_template,
                        'name': rate_modifier.name,
                        'modifier_type': 'discount',
                        'applies_to': 'guest_type',
                        'value': rate_modifier.discount_percent,
                        'stack_order': 40,
                        'channel': rate_modifier.channel,
                        'is_active': True,
                    }
                )


def reverse_migration(apps, schema_editor):
    """Reverse the data migration (delete created PropertyModifiers)."""
    PropertyModifier = apps.get_model('pricing', 'PropertyModifier')
    ModifierTemplate = apps.get_model('pricing', 'ModifierTemplate')
    
    # Only delete auto-migrated ones (those with specific code patterns)
    PropertyModifier.objects.filter(
        code__startswith='season-'
    ).delete()
    PropertyModifier.objects.filter(
        code__startswith='channel-'
    ).delete()
    PropertyModifier.objects.filter(
        code__startswith='modifier-'
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_daterateoverride_daterateoverrideperiod'),
    ]

    operations = [
        # =====================================================================
        # ADD FIELDS TO PROPERTY
        # =====================================================================
        migrations.AddField(
            model_name='property',
            name='service_charge_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('10.00'),
                help_text='Service charge percentage (e.g., 10.00 for 10%)',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('16.00'),
                help_text='Tax percentage (e.g., 16.00 for 16% GST)',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_on_service_charge',
            field=models.BooleanField(
                default=True,
                help_text='Whether tax applies to subtotal + service charge',
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='min_rate_warning',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Warn if any rate falls below this amount',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='max_discount_warning',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal('40.00'),
                help_text='Warn if total discount percentage exceeds this value',
                max_digits=5,
                null=True,
            ),
        ),
        
        # =====================================================================
        # CREATE MODIFIER TEMPLATE
        # =====================================================================
        migrations.CreateModel(
            name='ModifierTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Season Index')", max_length=100)),
                ('code', models.SlugField(help_text='Unique code within organization')),
                ('description', models.TextField(blank=True)),
                ('modifier_type', models.CharField(
                    choices=[
                        ('index', 'Index/Multiplier'),
                        ('discount', 'Discount'),
                        ('surcharge', 'Surcharge'),
                    ],
                    max_length=20,
                )),
                ('applies_to', models.CharField(
                    choices=[
                        ('season', 'Season'),
                        ('room_type', 'Room Type'),
                        ('channel', 'Channel'),
                        ('promo', 'Promotion/Offer'),
                        ('los', 'Length of Stay'),
                        ('booking_window', 'Booking Window'),
                        ('guest_type', 'Guest Type'),
                    ],
                    max_length=20,
                )),
                ('default_value', models.DecimalField(
                    decimal_places=2,
                    default=Decimal('0.00'),
                    max_digits=6,
                )),
                ('stack_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='modifier_templates',
                    to='pricing.organization',
                )),
            ],
            options={
                'ordering': ['organization', 'stack_order', 'name'],
                'unique_together': {('organization', 'code')},
                'verbose_name': 'Modifier Template',
                'verbose_name_plural': 'Modifier Templates',
            },
        ),
        
        # =====================================================================
        # CREATE PROPERTY MODIFIER
        # =====================================================================
        migrations.CreateModel(
            name='PropertyModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('modifier_type', models.CharField(
                    choices=[
                        ('index', 'Index/Multiplier'),
                        ('discount', 'Discount'),
                        ('surcharge', 'Surcharge'),
                    ],
                    max_length=20,
                )),
                ('applies_to', models.CharField(
                    choices=[
                        ('season', 'Season'),
                        ('room_type', 'Room Type'),
                        ('channel', 'Channel'),
                        ('promo', 'Promotion/Offer'),
                        ('los', 'Length of Stay'),
                        ('booking_window', 'Booking Window'),
                        ('guest_type', 'Guest Type'),
                    ],
                    max_length=20,
                )),
                ('value', models.DecimalField(
                    decimal_places=2,
                    default=Decimal('0.00'),
                    help_text='For index: multiplier. For discount/surcharge: percentage',
                    max_digits=6,
                )),
                ('stack_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('min_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('max_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('min_advance_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_advance_days', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pricing_modifiers',
                    to='pricing.property',
                )),
                ('template', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='property_instances',
                    to='pricing.modifiertemplate',
                )),
                ('season', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pricing_modifiers',
                    to='pricing.season',
                )),
                ('room_type', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pricing_modifiers',
                    to='pricing.roomtype',
                )),
                ('channel', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pricing_modifiers',
                    to='pricing.channel',
                )),
            ],
            options={
                'ordering': ['hotel', 'stack_order', 'name'],
                'unique_together': {('hotel', 'code')},
                'verbose_name': 'Property Modifier',
                'verbose_name_plural': 'Property Modifiers',
            },
        ),
        
        # =====================================================================
        # CREATE MODIFIER RULE
        # =====================================================================
        migrations.CreateModel(
            name='ModifierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(
                    choices=[
                        ('channel_only', 'Only for specific channels'),
                        ('exclude_channel', 'Exclude from specific channels'),
                        ('room_type_only', 'Only for specific room types'),
                        ('exclude_room_type', 'Exclude from specific room types'),
                        ('not_with', 'Cannot combine with other modifiers'),
                        ('requires', 'Requires other modifiers to be active'),
                        ('season_only', 'Only for specific seasons'),
                        ('exclude_season', 'Exclude from specific seasons'),
                    ],
                    max_length=20,
                )),
                ('is_active', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('modifier', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rules',
                    to='pricing.propertymodifier',
                )),
                ('channels', models.ManyToManyField(
                    blank=True,
                    related_name='modifier_rules',
                    to='pricing.channel',
                )),
                ('room_types', models.ManyToManyField(
                    blank=True,
                    related_name='modifier_rules',
                    to='pricing.roomtype',
                )),
                ('seasons', models.ManyToManyField(
                    blank=True,
                    related_name='modifier_rules',
                    to='pricing.season',
                )),
                ('other_modifiers', models.ManyToManyField(
                    blank=True,
                    related_name='referenced_by_rules',
                    to='pricing.propertymodifier',
                )),
            ],
            options={
                'ordering': ['modifier', 'rule_type'],
                'verbose_name': 'Modifier Rule',
                'verbose_name_plural': 'Modifier Rules',
            },
        ),
        
        # =====================================================================
        # DATA MIGRATIONS
        # =====================================================================
        migrations.RunPython(create_default_templates, migrations.RunPython.noop),
        migrations.RunPython(migrate_existing_data, reverse_migration),
    ]
