# Generated by Django 5.0.1 on 2026-02-05 08:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_property_max_discount_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiertemplate',
            name='is_stacked',
            field=models.BooleanField(default=False, help_text='Is this a combined/stacked modifier?'),
        ),
        migrations.AddField(
            model_name='modifiertemplate',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Can this modifier be stacked with other stackable modifiers?'),
        ),
        migrations.AddField(
            model_name='modifiertemplate',
            name='stacked_from',
            field=models.ManyToManyField(blank=True, help_text='Source modifiers if this is a stacked modifier', related_name='stacked_into', to='pricing.modifiertemplate'),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text='Channels this rule references', related_name='modifier_rules', to='pricing.channel'),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='error_message',
            field=models.CharField(blank=True, help_text='Custom error message when rule fails', max_length=200),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this rule is active'),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='modifier',
            field=models.ForeignKey(help_text='Modifier this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.propertymodifier'),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='other_modifiers',
            field=models.ManyToManyField(blank=True, help_text='Other modifiers this rule references', related_name='referenced_by_rules', to='pricing.propertymodifier'),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='room_types',
            field=models.ManyToManyField(blank=True, help_text='Room types this rule references', related_name='modifier_rules', to='pricing.roomtype'),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='rule_type',
            field=models.CharField(choices=[('channel_only', 'Only for specific channels'), ('exclude_channel', 'Exclude from specific channels'), ('room_type_only', 'Only for specific room types'), ('exclude_room_type', 'Exclude from specific room types'), ('not_with', 'Cannot combine with other modifiers'), ('requires', 'Requires other modifiers to be active'), ('season_only', 'Only for specific seasons'), ('exclude_season', 'Exclude from specific seasons')], help_text='Type of rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='modifierrule',
            name='seasons',
            field=models.ManyToManyField(blank=True, help_text='Seasons this rule references', related_name='modifier_rules', to='pricing.season'),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='applies_to',
            field=models.CharField(choices=[('season', 'Season'), ('room_type', 'Room Type'), ('channel', 'Channel'), ('promo', 'Promotion/Offer'), ('los', 'Length of Stay'), ('booking_window', 'Booking Window'), ('guest_type', 'Guest Type')], help_text='What entity this modifier is linked to', max_length=20),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='code',
            field=models.SlugField(help_text="Unique code (e.g., 'season-index', 'channel-discount')"),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='default_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default value for new property modifiers', max_digits=6),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this modifier does'),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is active'),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='modifier_type',
            field=models.CharField(choices=[('index', 'Index/Multiplier'), ('discount', 'Discount'), ('surcharge', 'Surcharge')], help_text='How the value is interpreted', max_length=20),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='name',
            field=models.CharField(help_text="Template name (e.g., 'Season Index', 'Channel Discount')", max_length=100),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='organization',
            field=models.ForeignKey(help_text='Organization this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modifier_templates', to='pricing.organization'),
        ),
        migrations.AlterField(
            model_name='modifiertemplate',
            name='stack_order',
            field=models.PositiveIntegerField(default=100, help_text='Order in stacking calculation (lower = applied first)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_on_service_charge',
            field=models.BooleanField(default=True, help_text='Whether tax is calculated on subtotal + service charge (True) or just subtotal (False)'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='applies_to',
            field=models.CharField(choices=[('season', 'Season'), ('room_type', 'Room Type'), ('channel', 'Channel'), ('promo', 'Promotion/Offer'), ('los', 'Length of Stay'), ('booking_window', 'Booking Window'), ('guest_type', 'Guest Type')], help_text='What entity this modifier is linked to', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='channel',
            field=models.ForeignKey(blank=True, help_text="Channel this modifier applies to (if applies_to='channel')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_modifiers', to='pricing.channel'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='code',
            field=models.SlugField(help_text='Unique code within property'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='description',
            field=models.TextField(blank=True, help_text='Description or notes'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='hotel',
            field=models.ForeignKey(help_text='Property this modifier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_modifiers', to='pricing.property'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this modifier is active'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='max_advance_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum days in advance for booking window modifier', null=True),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='max_nights',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum nights for LOS modifier', null=True),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='min_advance_days',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum days in advance for booking window modifier', null=True),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='min_nights',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum nights for LOS modifier', null=True),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='modifier_type',
            field=models.CharField(choices=[('index', 'Index/Multiplier'), ('discount', 'Discount'), ('surcharge', 'Surcharge')], help_text='How the value is interpreted', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='name',
            field=models.CharField(help_text="Modifier name (e.g., 'Peak Season', 'OTA Discount')", max_length=100),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text="Room type this modifier applies to (if applies_to='room_type')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_modifiers', to='pricing.roomtype'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='season',
            field=models.ForeignKey(blank=True, help_text="Season this modifier applies to (if applies_to='season')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_modifiers', to='pricing.season'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='stack_order',
            field=models.PositiveIntegerField(default=100, help_text='Order in stacking calculation (lower = applied first)'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this modifier is based on (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_instances', to='pricing.modifiertemplate'),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Start date for this modifier (for promos)', null=True),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='valid_until',
            field=models.DateField(blank=True, help_text='End date for this modifier (for promos)', null=True),
        ),
        migrations.AlterField(
            model_name='propertymodifier',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For index: multiplier (1.20 = +20%). For discount/surcharge: percentage (10 = 10%)', max_digits=6),
        ),
    ]
