# Generated by Django 5.0.1 on 2026-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_modifiertemplate_is_stacked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemodifier',
            name='is_stacked',
            field=models.BooleanField(default=False, help_text='Is this a combined/stacked modifier?'),
        ),
        migrations.AddField(
            model_name='ratemodifier',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Can this modifier be stacked with other stackable modifiers?'),
        ),
        migrations.AddField(
            model_name='ratemodifier',
            name='stacked_from',
            field=models.ManyToManyField(blank=True, help_text='Source modifiers if this is a stacked modifier', related_name='stacked_into', to='pricing.ratemodifier'),
        ),
    ]
