# Generated by Django 6.0.2 on 2026-02-12 07:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_ratemodifier_is_stacked_ratemodifier_stackable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Room features/description (e.g., 'Ocean view, balcony, premium amenities')"),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='target_occupancy',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Target occupancy % for this room type (e.g., 75.00 for 75%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='RoomTypeSeasonModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to season index for this room type (e.g., 1.35 means 35% amplification of the season index)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('notes', models.CharField(blank=True, default='', help_text="Optional notes (e.g., 'Honeymoon market less seasonal')", max_length=200)),
                ('room_type', models.ForeignKey(help_text='Room type this modifier applies to', on_delete=django.db.models.deletion.CASCADE, related_name='season_modifiers', to='pricing.roomtype')),
                ('season', models.ForeignKey(help_text='Season this modifier applies to', on_delete=django.db.models.deletion.CASCADE, related_name='room_type_modifiers', to='pricing.season')),
            ],
            options={
                'verbose_name': 'Room Type Season Modifier',
                'verbose_name_plural': 'Room Type Season Modifiers',
                'ordering': ['season__start_date', 'room_type__sort_order'],
                'unique_together': {('room_type', 'season')},
            },
        ),
    ]
