# Generated by Django 5.0.1 on 2026-01-19 21:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion

def create_default_org_and_property(apps, schema_editor):
    """
    Data migration: Create default organization and property.
    Assign all existing records to the default property.
    """
    Organization = apps.get_model('pricing', 'Organization')
    Property = apps.get_model('pricing', 'Property')
    
    # Get all models that need property assignment
    Season = apps.get_model('pricing', 'Season')
    RoomType = apps.get_model('pricing', 'RoomType')
    RatePlan = apps.get_model('pricing', 'RatePlan')
    Channel = apps.get_model('pricing', 'Channel')
    RateModifier = apps.get_model('pricing', 'RateModifier')
    
    # Create default organization
    org, _ = Organization.objects.get_or_create(
        code='default',
        defaults={
            'name': 'My Hotel Group',
            'default_currency': 'USD',
            'currency_symbol': '$',
            'is_active': True,
        }
    )
    
    # Create default property (Biosphere Inn based on existing data)
    prop, _ = Property.objects.get_or_create(
        organization=org,
        code='biosphere-inn',
        defaults={
            'name': 'Biosphere Inn',
            'location': 'Dharavandhoo, Baa Atoll, Maldives',
            'timezone': 'Indian/Maldives',
            'reference_base_rate': Decimal('100.00'),
            'currency_symbol': '$',
            'is_active': True,
        }
    )
    
    # Assign all existing records to this property
    Season.objects.filter(property__isnull=True).update(property=prop)
    RoomType.objects.filter(property__isnull=True).update(property=prop)
    RatePlan.objects.filter(property__isnull=True).update(property=prop)
    Channel.objects.filter(property__isnull=True).update(property=prop)
    RateModifier.objects.filter(property__isnull=True).update(property=prop)


def reverse_migration(apps, schema_editor):
    """Reverse: Do nothing (keep data)."""
    pass


class Migration(migrations.Migration):
    """
    Add multi-organization support.
    
    IMPORTANT: Update 'dependencies' to match your last migration!
    """
    
    dependencies = [
        # UPDATE THIS to your last migration file name (without .py)
        ('pricing', '0008_fileimport_bookingsource_guest_reservation'),
    ]

    operations = [
        # STEP 1: Create Organization model
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Organization name", max_length=200)),
                ('code', models.SlugField(help_text="URL-friendly code", unique=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        
        # STEP 2: Create Property model
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Property name", max_length=200)),
                ('code', models.SlugField(help_text="URL-friendly code")),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='Indian/Maldives', max_length=50)),
                ('reference_base_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='pricing.organization')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        
        # STEP 3: Add nullable property FK to existing models
        migrations.AddField(
            model_name='season',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='pricing.property'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='pricing.property'),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='pricing.property'),
        ),
        migrations.AddField(
            model_name='channel',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='pricing.property'),
        ),
        migrations.AddField(
            model_name='ratemodifier',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_modifiers', to='pricing.property'),
        ),
        
        # STEP 4: Run data migration
        migrations.RunPython(create_default_org_and_property, reverse_migration),
        
        # STEP 5: Make property FK required
        migrations.AlterField(
            model_name='season',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='pricing.property'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='pricing.property'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='pricing.property'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='pricing.property'),
        ),
        migrations.AlterField(
            model_name='ratemodifier',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_modifiers', to='pricing.property'),
        ),
    ]